jobs:
- name: first job
  public: true
  plan:
    - task: sayhello
      config:
          platform: linux
          image_resource: 
              type: docker-image
              source: {repository: busybox}
          
          run:
              path: echo
              args: 
              - write by marion
              - write by 21vpaas
